version: "3.8"

# ============================================================================
# 🛠️ Définition des volumes persistants
# ============================================================================
volumes:
  postgres-data:
    driver: local    # Volume pour la base PostgreSQL
  kestra-data:
    driver: local    # Volume pour le stockage interne de Kestra
  minio-data:
    driver: local    # Volume pour les données stockées dans MinIO

# ============================================================================
# 🚀 Définition des services à déployer
# ============================================================================
services:

  # --------------------------------------------------------------------------
  # 📦 PostgreSQL — Base de données pour Kestra
  # --------------------------------------------------------------------------
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - hybrid_net

  # --------------------------------------------------------------------------
  # ☁️ MinIO — Serveur de stockage compatible S3
  # --------------------------------------------------------------------------
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --address ":9000" --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:9000"    # Port API S3
      - "9001:9001"    # Port Console WebUI MinIO
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    networks:
      - hybrid_net

  # --------------------------------------------------------------------------
  # ⚙️ Kestra — Orchestrateur de workflows
  # --------------------------------------------------------------------------
  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    restart: unless-stopped
    user: "root"        # Important pour accéder au Docker socket
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd

    ports:
      - "8080:8080"     # Interface Web Kestra
      - "8081:8081"     # API interne Kestra
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              enabled: false
              username: "admin@example.com"
              password: kestra
          repository:
            type: postgres
          storage:
            type: s3
            s3:
              endpoint: http://minio:9000
              region: us-east-1
              bucket: bottleneck
              accessKey: AKIAIOSFODNN7EXAMPLE
              secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
              forcePathStyle: true
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
      KESTRA_PLUGINS: |
        - io.kestra.plugin.scripts.exec
    depends_on:
      postgres:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - hybrid_net

# ============================================================================
# 🌐 Définition du réseau commun
# ============================================================================
networks:
  hybrid_net:
    driver: bridge

# ============================================================================
# 📋 Remarques importantes
# ============================================================================
# - Tous les services communiquent via le réseau "hybrid_net"
# - Kestra utilise MinIO comme stockage principal
# - Ports exposés localement pour accès web (MinIO :9001, Kestra :8080)
