version: '3.8'

# ========================
# Volumes persistants
# ========================
volumes:
  postgres-data:       # Volume pour les données PostgreSQL
    driver: local

  kestra-data:         # Volume pour le stockage interne de Kestra
    driver: local

  kestra-outputs:      # Volume pour les fichiers de sortie de Kestra
    driver: local

# ========================
# Services
# ========================
services:

  # ------------------------
  # Base de données PostgreSQL
  # ------------------------
  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kestra"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------------------------
  # Serveur principal Kestra
  # ------------------------
  kestra:
    image: kestra/kestra:0.15.0  # Version stable
    restart: unless-stopped
    user: root                   # Permet l'accès aux chemins montés en lecture/écriture
    command: server standalone
    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - kestra-data:/app/storage                        # Stockage interne Kestra
      - kestra-outputs:/mnt/outputs                     # Dossier de sortie Kestra
      - /var/run/docker.sock:/var/run/docker.sock       # Nécessaire pour lancer des conteneurs via Kestra
      - ./workflows:/app/workflows                      # Workflows locaux (YAML)
      - /mnt/f/1.Boulot/03_Github/orchestration-bottleneck:/mnt/orchestration  # Accès aux fichiers locaux sur F:

    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          server:
            basicAuth:
              enabled: false  # Authentification désactivée pour dev
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres

    ports:
      - "8080:8080"  # Interface web
      - "8081:8081"  # API REST

  # ------------------------
  # Explorateur de fichiers optionnel
  # ------------------------
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - kestra-outputs:/srv
    ports:
      - "8082:80"    # Interface Filebrowser
